[2024-11-24T19:25:18.719+0000] {processor.py:157} INFO - Started process (PID=6868) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:18.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:25:18.720+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:25:18.720+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:18.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:18.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.012 seconds
[2024-11-24T19:25:28.932+0000] {processor.py:157} INFO - Started process (PID=7104) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:28.933+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:25:28.934+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:25:28.934+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:28.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:28.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.019 seconds
[2024-11-24T19:25:39.334+0000] {processor.py:157} INFO - Started process (PID=7340) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:39.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:25:39.337+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:25:39.336+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:39.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:39.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.018 seconds
[2024-11-24T19:25:49.574+0000] {processor.py:157} INFO - Started process (PID=7576) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:49.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:25:49.577+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:25:49.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:49.580+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:49.593+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-11-24T19:25:59.817+0000] {processor.py:157} INFO - Started process (PID=7812) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:59.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:25:59.819+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:25:59.818+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:59.821+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:25:59.833+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.020 seconds
[2024-11-24T19:26:10.051+0000] {processor.py:157} INFO - Started process (PID=8048) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:10.052+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:26:10.052+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:26:10.052+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:10.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:10.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.016 seconds
[2024-11-24T19:26:20.310+0000] {processor.py:157} INFO - Started process (PID=8284) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:20.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:26:20.311+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:26:20.311+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:20.313+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:20.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.014 seconds
[2024-11-24T19:26:30.484+0000] {processor.py:157} INFO - Started process (PID=8520) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:30.486+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:26:30.487+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:26:30.486+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:30.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:30.502+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-11-24T19:26:40.933+0000] {processor.py:157} INFO - Started process (PID=8756) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:40.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:26:40.935+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:26:40.934+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:40.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:40.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.019 seconds
[2024-11-24T19:26:51.350+0000] {processor.py:157} INFO - Started process (PID=8992) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:51.351+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:26:51.352+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:26:51.352+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:51.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:26:51.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.020 seconds
[2024-11-24T19:27:01.800+0000] {processor.py:157} INFO - Started process (PID=9228) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:01.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:27:01.804+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:27:01.803+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:01.823+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:01.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2024-11-24T19:27:12.154+0000] {processor.py:157} INFO - Started process (PID=9464) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:12.155+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:27:12.156+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:27:12.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:12.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:12.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.018 seconds
[2024-11-24T19:27:13.435+0000] {processor.py:157} INFO - Started process (PID=9509) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:13.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:27:13.436+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:27:13.436+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:13.438+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:13.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.010 seconds
[2024-11-24T19:27:23.765+0000] {processor.py:157} INFO - Started process (PID=9705) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:23.767+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:27:23.767+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:27:23.767+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:23.774+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:23.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:27:34.047+0000] {processor.py:157} INFO - Started process (PID=9941) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:34.048+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:27:34.049+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:27:34.049+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:34.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:34.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2024-11-24T19:27:44.448+0000] {processor.py:157} INFO - Started process (PID=10177) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:44.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:27:44.450+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:27:44.449+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:44.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:44.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2024-11-24T19:27:54.731+0000] {processor.py:157} INFO - Started process (PID=10413) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:54.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:27:54.733+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:27:54.733+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:54.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:27:54.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-11-24T19:28:05.405+0000] {processor.py:157} INFO - Started process (PID=10649) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:05.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:28:05.407+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:28:05.407+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:05.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:05.429+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-11-24T19:28:15.542+0000] {processor.py:157} INFO - Started process (PID=10885) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:15.544+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:28:15.545+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:28:15.544+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:15.547+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:15.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2024-11-24T19:28:25.644+0000] {processor.py:157} INFO - Started process (PID=11121) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:25.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:28:25.645+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:28:25.645+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:25.657+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:25.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:28:36.464+0000] {processor.py:157} INFO - Started process (PID=11357) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:36.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:28:36.466+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:28:36.465+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:36.471+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:36.484+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-11-24T19:28:46.865+0000] {processor.py:157} INFO - Started process (PID=11593) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:46.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:28:46.867+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:28:46.866+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:46.870+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:46.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2024-11-24T19:28:57.150+0000] {processor.py:157} INFO - Started process (PID=11829) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:57.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:28:57.152+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:28:57.152+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:57.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:28:57.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-11-24T19:29:07.562+0000] {processor.py:157} INFO - Started process (PID=12065) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:07.563+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:29:07.564+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:07.564+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:07.571+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:07.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-11-24T19:29:08.804+0000] {processor.py:157} INFO - Started process (PID=12098) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:08.805+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:29:08.806+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:08.806+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:08.811+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:08.853+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:08.853+0000] {manager.py:499} INFO - Created Permission View: %s
[2024-11-24T19:29:08.856+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:08.856+0000] {manager.py:499} INFO - Created Permission View: %s
[2024-11-24T19:29:08.858+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:08.858+0000] {manager.py:499} INFO - Created Permission View: %s
[2024-11-24T19:29:08.858+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:08.858+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:29:08.863+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:08.863+0000] {dag.py:2963} INFO - Creating ORM DAG for test_dag
[2024-11-24T19:29:08.866+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:08.866+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:29:08.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2024-11-24T19:29:19.181+0000] {processor.py:157} INFO - Started process (PID=12316) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:19.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:29:19.184+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:19.184+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:19.191+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:19.204+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:19.204+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:29:19.218+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:19.218+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:29:19.231+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2024-11-24T19:29:29.452+0000] {processor.py:157} INFO - Started process (PID=12552) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:29.453+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:29:29.454+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:29.454+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:29.463+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:29.472+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:29.472+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:29:29.488+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:29.488+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:29:29.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2024-11-24T19:29:39.779+0000] {processor.py:157} INFO - Started process (PID=12788) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:39.780+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:29:39.781+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:39.781+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:39.787+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:39.802+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:39.801+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:29:39.813+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:39.813+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:29:39.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-11-24T19:29:50.055+0000] {processor.py:157} INFO - Started process (PID=13024) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:50.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:29:50.058+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:50.058+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:50.065+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:29:50.077+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:50.077+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:29:50.090+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:29:50.090+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:29:50.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-11-24T19:30:00.345+0000] {processor.py:157} INFO - Started process (PID=13260) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:00.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:30:00.347+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:00.347+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:00.353+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:00.366+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:00.366+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:30:00.378+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:00.378+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:30:00.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-11-24T19:30:10.624+0000] {processor.py:157} INFO - Started process (PID=13496) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:10.625+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:30:10.626+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:10.626+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:10.634+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:10.647+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:10.647+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:30:10.661+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:10.661+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:30:10.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-11-24T19:30:21.308+0000] {processor.py:157} INFO - Started process (PID=13732) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:21.309+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:30:21.310+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:21.310+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:21.315+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:21.332+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:21.332+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:30:21.346+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:21.346+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:30:21.356+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2024-11-24T19:30:31.722+0000] {processor.py:157} INFO - Started process (PID=13968) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:31.723+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:30:31.724+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:31.724+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:31.730+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:31.745+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:31.745+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:30:31.758+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:31.758+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:30:31.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-11-24T19:30:42.209+0000] {processor.py:157} INFO - Started process (PID=14204) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:42.210+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:30:42.211+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:42.211+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:42.219+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:42.232+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:42.232+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:30:42.248+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:42.248+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:30:42.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-11-24T19:30:52.544+0000] {processor.py:157} INFO - Started process (PID=14440) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:52.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:30:52.546+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:52.546+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:52.553+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:30:52.572+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:52.572+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:30:52.585+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:30:52.585+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:30:52.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2024-11-24T19:31:02.951+0000] {processor.py:157} INFO - Started process (PID=14676) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:02.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:31:02.953+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:02.952+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:02.957+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:02.969+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:02.969+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:31:02.980+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:02.980+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:31:02.990+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-11-24T19:31:13.198+0000] {processor.py:157} INFO - Started process (PID=14912) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:13.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:31:13.200+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:13.200+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:13.208+0000] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag']) retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:13.220+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:13.220+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2024-11-24T19:31:13.234+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:13.234+0000] {dag.py:3722} INFO - Setting next_dagrun for test_dag to None, run_after=None
[2024-11-24T19:31:13.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-11-24T19:31:16.447+0000] {processor.py:157} INFO - Started process (PID=14952) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:16.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:31:16.449+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:16.449+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:16.457+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:16.456+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:31:16.458+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:16.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-11-24T19:31:26.784+0000] {processor.py:157} INFO - Started process (PID=15188) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:26.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:31:26.787+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:26.787+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:26.804+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:26.802+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:31:26.804+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:26.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-11-24T19:31:37.236+0000] {processor.py:157} INFO - Started process (PID=15424) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:37.237+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:31:37.237+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:37.237+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:37.243+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:37.242+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:31:37.243+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:37.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-11-24T19:31:47.498+0000] {processor.py:157} INFO - Started process (PID=15660) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:47.499+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:31:47.500+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:47.499+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:47.508+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:47.504+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:31:47.509+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:47.526+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-11-24T19:31:57.829+0000] {processor.py:157} INFO - Started process (PID=15896) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:57.830+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:31:57.831+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:57.831+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:57.840+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:31:57.834+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:31:57.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:31:57.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-11-24T19:32:04.912+0000] {processor.py:157} INFO - Started process (PID=16097) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:04.913+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:32:04.913+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:04.913+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:04.918+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:04.917+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:32:04.920+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:04.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-11-24T19:32:15.360+0000] {processor.py:157} INFO - Started process (PID=16333) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:15.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:32:15.362+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:15.362+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:15.373+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:15.371+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:32:15.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:15.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-11-24T19:32:25.661+0000] {processor.py:157} INFO - Started process (PID=16569) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:25.663+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:32:25.664+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:25.664+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:25.678+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:25.674+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:32:25.680+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:25.701+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-11-24T19:32:36.476+0000] {processor.py:157} INFO - Started process (PID=16805) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:36.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:32:36.477+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:36.477+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:36.486+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:36.485+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:32:36.486+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:36.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:32:47.163+0000] {processor.py:157} INFO - Started process (PID=17041) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:47.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:32:47.165+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:47.165+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:47.173+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:47.172+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:32:47.173+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:47.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-11-24T19:32:57.765+0000] {processor.py:157} INFO - Started process (PID=17277) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:57.766+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:32:57.766+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:57.766+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:57.769+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:32:57.768+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:32:57.773+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:32:57.784+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.022 seconds
[2024-11-24T19:33:08.677+0000] {processor.py:157} INFO - Started process (PID=17513) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:08.678+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:33:08.680+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:08.679+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:08.690+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:08.686+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:33:08.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:08.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-11-24T19:33:19.104+0000] {processor.py:157} INFO - Started process (PID=17749) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:19.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:33:19.106+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:19.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:19.112+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:19.110+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:33:19.113+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:19.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-11-24T19:33:29.459+0000] {processor.py:157} INFO - Started process (PID=17985) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:29.460+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:33:29.460+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:29.460+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:29.471+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:29.466+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:33:29.472+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:29.489+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-11-24T19:33:40.092+0000] {processor.py:157} INFO - Started process (PID=18221) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:40.094+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:33:40.094+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:40.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:40.104+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:40.103+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:33:40.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:40.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-11-24T19:33:50.508+0000] {processor.py:157} INFO - Started process (PID=18457) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:50.509+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:33:50.510+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:50.509+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:50.517+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:33:50.512+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:33:50.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:33:50.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-11-24T19:34:00.951+0000] {processor.py:157} INFO - Started process (PID=18693) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:00.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:34:00.953+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:00.953+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:00.961+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:00.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:34:00.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:00.978+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-11-24T19:34:11.464+0000] {processor.py:157} INFO - Started process (PID=18929) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:11.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:34:11.467+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:11.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:11.475+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:11.470+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:34:11.476+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:11.494+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-11-24T19:34:21.894+0000] {processor.py:157} INFO - Started process (PID=19165) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:21.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:34:21.896+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:21.896+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:21.900+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:21.899+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:34:21.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:21.917+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-11-24T19:34:32.325+0000] {processor.py:157} INFO - Started process (PID=19401) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:32.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:34:32.327+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:32.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:32.337+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:32.336+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:34:32.337+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:32.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-11-24T19:34:42.830+0000] {processor.py:157} INFO - Started process (PID=19637) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:42.831+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:34:42.832+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:42.832+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:42.841+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:42.837+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:34:42.842+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:42.858+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-11-24T19:34:53.404+0000] {processor.py:157} INFO - Started process (PID=19873) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:53.405+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:34:53.406+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:53.406+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:53.416+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:34:53.410+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:34:53.418+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:34:53.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-11-24T19:35:03.814+0000] {processor.py:157} INFO - Started process (PID=20109) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:03.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:35:03.816+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:03.815+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:03.830+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:03.822+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:35:03.831+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:03.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-11-24T19:35:14.259+0000] {processor.py:157} INFO - Started process (PID=20345) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:14.260+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:35:14.261+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:14.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:14.264+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:14.263+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:35:14.265+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:14.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.022 seconds
[2024-11-24T19:35:24.779+0000] {processor.py:157} INFO - Started process (PID=20581) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:24.780+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:35:24.781+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:24.781+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:24.791+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:24.784+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:35:24.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:24.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-11-24T19:35:35.141+0000] {processor.py:157} INFO - Started process (PID=20817) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:35.142+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:35:35.143+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:35.143+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:35.158+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:35.151+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:35:35.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:35.172+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-11-24T19:35:45.604+0000] {processor.py:157} INFO - Started process (PID=21053) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:45.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:35:45.606+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:45.606+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:45.615+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:45.611+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:35:45.616+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:45.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-11-24T19:35:56.103+0000] {processor.py:157} INFO - Started process (PID=21289) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:56.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:35:56.105+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:56.105+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:56.110+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:35:56.108+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:35:56.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:35:56.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-11-24T19:36:06.574+0000] {processor.py:157} INFO - Started process (PID=21525) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:06.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:36:06.576+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:06.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:06.585+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:06.579+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:36:06.586+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:06.603+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-11-24T19:36:17.242+0000] {processor.py:157} INFO - Started process (PID=21761) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:17.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:36:17.249+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:17.249+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:17.259+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:17.258+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:36:17.259+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:17.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-11-24T19:36:27.869+0000] {processor.py:157} INFO - Started process (PID=21997) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:27.871+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:36:27.874+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:27.874+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:27.879+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:27.878+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:36:27.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:27.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-11-24T19:36:38.492+0000] {processor.py:157} INFO - Started process (PID=22233) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:38.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:36:38.494+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:38.494+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:38.503+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:38.501+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:36:38.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:38.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-11-24T19:36:49.064+0000] {processor.py:157} INFO - Started process (PID=22469) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:49.066+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:36:49.067+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:49.066+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:49.079+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:49.072+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:36:49.080+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:49.099+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-11-24T19:36:59.783+0000] {processor.py:157} INFO - Started process (PID=22705) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:59.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:36:59.786+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:59.786+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:59.794+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:36:59.792+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:36:59.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:36:59.811+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-11-24T19:37:10.474+0000] {processor.py:157} INFO - Started process (PID=22941) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:10.475+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:37:10.477+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:10.476+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:10.482+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:10.480+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:37:10.482+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:10.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-11-24T19:37:21.026+0000] {processor.py:157} INFO - Started process (PID=23177) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:21.027+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:37:21.028+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:21.027+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:21.040+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:21.038+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:37:21.040+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:21.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-11-24T19:37:31.551+0000] {processor.py:157} INFO - Started process (PID=23413) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:31.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:37:31.553+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:31.553+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:31.557+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:31.555+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:37:31.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:31.572+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-11-24T19:37:42.050+0000] {processor.py:157} INFO - Started process (PID=23649) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:42.052+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:37:42.053+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:42.053+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:42.057+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:42.056+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:37:42.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:42.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:37:52.563+0000] {processor.py:157} INFO - Started process (PID=23885) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:52.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:37:52.564+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:52.564+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:52.571+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:37:52.568+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:37:52.571+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:37:52.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-11-24T19:38:03.047+0000] {processor.py:157} INFO - Started process (PID=24121) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:03.048+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:38:03.049+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:03.048+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:03.057+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:03.056+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:38:03.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:03.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-11-24T19:38:13.543+0000] {processor.py:157} INFO - Started process (PID=24357) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:13.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:38:13.546+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:13.546+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:13.551+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:13.550+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:38:13.552+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:13.568+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-11-24T19:38:23.974+0000] {processor.py:157} INFO - Started process (PID=24593) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:23.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:38:23.977+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:23.977+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:23.982+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:23.980+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:38:23.985+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:24.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-11-24T19:38:34.593+0000] {processor.py:157} INFO - Started process (PID=24829) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:34.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:38:34.597+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:34.596+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:34.604+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:34.600+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:38:34.604+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:34.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-11-24T19:38:45.099+0000] {processor.py:157} INFO - Started process (PID=25065) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:45.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:38:45.100+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:45.100+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:45.104+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:45.102+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:38:45.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:45.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-11-24T19:38:55.534+0000] {processor.py:157} INFO - Started process (PID=25301) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:55.535+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:38:55.536+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:55.535+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:55.543+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:38:55.542+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:38:55.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:38:55.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2024-11-24T19:39:05.961+0000] {processor.py:157} INFO - Started process (PID=25537) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:05.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:39:05.963+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:05.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:05.970+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:05.967+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:39:05.971+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:05.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-11-24T19:39:16.331+0000] {processor.py:157} INFO - Started process (PID=25773) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:16.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:39:16.332+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:16.332+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:16.342+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:16.335+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:39:16.343+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:16.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:39:26.800+0000] {processor.py:157} INFO - Started process (PID=26009) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:26.801+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:39:26.802+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:26.801+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:26.812+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:26.811+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:39:26.812+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:26.823+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-11-24T19:39:37.217+0000] {processor.py:157} INFO - Started process (PID=26245) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:37.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:39:37.219+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:37.219+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:37.223+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:37.222+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:39:37.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:37.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-11-24T19:39:47.625+0000] {processor.py:157} INFO - Started process (PID=26481) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:47.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:39:47.627+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:47.627+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:47.632+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:47.630+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:39:47.632+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:47.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2024-11-24T19:39:58.004+0000] {processor.py:157} INFO - Started process (PID=26717) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:58.005+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:39:58.006+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:58.006+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:58.013+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:39:58.008+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:39:58.014+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:39:58.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-11-24T19:40:08.357+0000] {processor.py:157} INFO - Started process (PID=26953) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:08.358+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:40:08.359+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:08.358+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:08.367+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:08.363+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:40:08.368+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:08.395+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-11-24T19:40:18.848+0000] {processor.py:157} INFO - Started process (PID=27189) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:18.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:40:18.850+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:18.850+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:18.857+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:18.856+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:40:18.857+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:18.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-11-24T19:40:29.250+0000] {processor.py:157} INFO - Started process (PID=27425) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:29.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:40:29.252+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:29.251+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:29.262+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:29.255+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:40:29.263+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:29.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-11-24T19:40:40.108+0000] {processor.py:157} INFO - Started process (PID=27661) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:40.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:40:40.112+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:40.112+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:40.128+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:40.127+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:40:40.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:40.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-11-24T19:40:50.646+0000] {processor.py:157} INFO - Started process (PID=27897) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:50.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:40:50.650+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:50.649+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:50.659+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:40:50.657+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:40:50.663+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:40:50.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-11-24T19:41:01.105+0000] {processor.py:157} INFO - Started process (PID=28133) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:01.107+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:41:01.108+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:01.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:01.111+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:01.110+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:41:01.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:01.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-11-24T19:41:11.513+0000] {processor.py:157} INFO - Started process (PID=28369) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:11.515+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:41:11.516+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:11.516+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:11.525+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:11.524+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:41:11.525+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:11.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-11-24T19:41:21.919+0000] {processor.py:157} INFO - Started process (PID=28605) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:21.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:41:21.922+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:21.922+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:21.932+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:21.927+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:41:21.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:21.947+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-11-24T19:41:32.345+0000] {processor.py:157} INFO - Started process (PID=28841) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:32.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:41:32.347+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:32.347+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:32.353+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:32.352+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:41:32.354+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:32.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.076 seconds
[2024-11-24T19:41:42.849+0000] {processor.py:157} INFO - Started process (PID=29077) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:42.851+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:41:42.852+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:42.851+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:42.859+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:42.858+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:41:42.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:42.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-11-24T19:41:53.324+0000] {processor.py:157} INFO - Started process (PID=29313) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:53.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:41:53.326+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:53.326+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:53.334+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:41:53.333+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:41:53.334+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:41:53.347+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:42:03.720+0000] {processor.py:157} INFO - Started process (PID=29549) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:03.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:42:03.722+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:03.722+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:03.730+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:03.729+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:42:03.731+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:03.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-11-24T19:42:14.104+0000] {processor.py:157} INFO - Started process (PID=29785) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:14.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:42:14.106+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:14.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:14.113+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:14.112+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:42:14.113+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:14.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-11-24T19:42:24.459+0000] {processor.py:157} INFO - Started process (PID=30021) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:24.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:42:24.461+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:24.461+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:24.465+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:24.464+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:42:24.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:24.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-11-24T19:42:34.869+0000] {processor.py:157} INFO - Started process (PID=30257) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:34.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:42:34.871+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:34.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:34.877+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:34.876+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:42:34.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:34.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:42:45.412+0000] {processor.py:157} INFO - Started process (PID=30493) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:45.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:42:45.415+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:45.415+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:45.423+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:45.422+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:42:45.423+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:45.435+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:42:55.785+0000] {processor.py:157} INFO - Started process (PID=30729) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:55.786+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:42:55.787+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:55.786+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:55.794+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:42:55.793+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:42:55.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:42:55.809+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-11-24T19:43:06.164+0000] {processor.py:157} INFO - Started process (PID=30965) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:06.166+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:43:06.167+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:06.167+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:06.171+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:06.170+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:43:06.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:06.189+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-11-24T19:43:16.839+0000] {processor.py:157} INFO - Started process (PID=31201) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:16.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:43:16.843+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:16.843+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:16.852+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:16.852+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:43:16.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:16.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-11-24T19:43:27.187+0000] {processor.py:157} INFO - Started process (PID=31437) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:27.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:43:27.189+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:27.188+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:27.193+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:27.191+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:43:27.193+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:27.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.022 seconds
[2024-11-24T19:43:37.576+0000] {processor.py:157} INFO - Started process (PID=31673) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:37.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:43:37.577+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:37.577+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:37.586+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:37.585+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:43:37.586+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:37.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-11-24T19:43:47.859+0000] {processor.py:157} INFO - Started process (PID=31909) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:47.861+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:43:47.862+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:47.861+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:47.868+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:47.866+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:43:47.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:47.880+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2024-11-24T19:43:58.306+0000] {processor.py:157} INFO - Started process (PID=32145) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:58.308+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:43:58.309+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:58.309+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:58.313+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:43:58.312+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:43:58.313+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:43:58.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-11-24T19:44:08.615+0000] {processor.py:157} INFO - Started process (PID=32381) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:08.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:44:08.618+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:08.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:08.622+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:08.621+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:44:08.622+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:08.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2024-11-24T19:44:18.886+0000] {processor.py:157} INFO - Started process (PID=32617) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:18.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:44:18.889+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:18.888+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:18.898+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:18.894+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:44:18.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:18.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-11-24T19:44:26.140+0000] {processor.py:157} INFO - Started process (PID=32843) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:26.141+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:44:26.142+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:26.142+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:26.301+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:26.300+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 51, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:44:26.302+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:26.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.176 seconds
[2024-11-24T19:44:36.637+0000] {processor.py:157} INFO - Started process (PID=33080) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:36.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:44:36.638+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:36.637+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:36.757+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:36.756+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 51, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:44:36.758+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:36.764+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.129 seconds
[2024-11-24T19:44:47.246+0000] {processor.py:157} INFO - Started process (PID=33317) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:47.248+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:44:47.249+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:47.249+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:47.420+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:47.419+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 51, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:44:47.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:47.435+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.193 seconds
[2024-11-24T19:44:49.389+0000] {processor.py:157} INFO - Started process (PID=33323) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:49.389+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:44:49.390+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:49.390+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:49.579+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:49.577+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 51, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:44:49.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:49.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.204 seconds
[2024-11-24T19:44:59.945+0000] {processor.py:157} INFO - Started process (PID=33560) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:44:59.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:44:59.947+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:44:59.946+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:45:00.107+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:45:00.106+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 51, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:45:00.107+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:45:00.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.171 seconds
[2024-11-24T19:45:10.333+0000] {processor.py:157} INFO - Started process (PID=33797) to work on /opt/airflow/dags/test_dag.py
[2024-11-24T19:45:10.334+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-24T19:45:10.334+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:45:10.334+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-24T19:45:10.526+0000] {logging_mixin.py:154} INFO - [2024-11-24T19:45:10.525+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 51, in <module>
    'start_date': dt.datetime.date(),
TypeError: descriptor 'date' of 'datetime.datetime' object needs an argument
[2024-11-24T19:45:10.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-24T19:45:10.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test_dag.py took 0.205 seconds
